SET IDENTITY_INSERT bancos ON;

INSERT INTO bancos (Codigo, Nome) VALUES (117,	'Advanced Cc Ltda')
INSERT INTO bancos (Codigo, Nome) VALUES (172,	'Albatross Ccv S.A')
INSERT INTO bancos (Codigo, Nome) VALUES (188,	'Ativa Investimentos S.A')
INSERT INTO bancos (Codigo, Nome) VALUES (280,	'Avista S.A. Crédito, Financiamento e Investimento')
INSERT INTO bancos (Codigo, Nome) VALUES (80,	'B&T Cc Ltda')
INSERT INTO bancos (Codigo, Nome) VALUES (654,	'Banco A.J.Renner S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (246,	'Banco ABC Brasil S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (246,	'Banco ABC Brasil S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (75,	'Banco ABN AMRO S.A')
INSERT INTO bancos (Codigo, Nome) VALUES (121,	'Banco Agibank S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (121,	'Banco Agibank S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (25,	'Banco Alfa S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (641,	'Banco Alvorada S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (65,	'Banco Andbank (Brasil) S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (213,	'Banco Arbi S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (96,	'Banco B3 S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (24,	'Banco BANDEPE S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (318,	'Banco BMG S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (752,	'Banco BNP Paribas Brasil S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (107,	'Banco BOCOM BBM S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (63,	'Banco Bradescard S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (36,	'Banco Bradesco BBI S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (122,	'Banco Bradesco BERJ S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (204,	'Banco Bradesco Cartões S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (394,	'Banco Bradesco Financiamentos S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (237,	'Banco Bradesco S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (218,	'Banco BS2 S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (208,	'Banco BTG Pactual S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (336,	'Banco C6 S.A – C6 Bank')
INSERT INTO bancos (Codigo, Nome) VALUES (473,	'Banco Caixa Geral – Brasil S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (412,	'Banco Capital S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (40,	'Banco Cargill S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (368,	'Banco Carrefour')
INSERT INTO bancos (Codigo, Nome) VALUES (266,	'Banco Cédula S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (739,	'Banco Cetelem S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (233,	'Banco Cifra S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (745,	'Banco Citibank S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (241,	'Banco Clássico S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (756,	'Banco Cooperativo do Brasil S.A. – BANCOOB')
INSERT INTO bancos (Codigo, Nome) VALUES (748,	'Banco Cooperativo Sicredi S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (748,	'Banco Cooperativo Sicredi S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (222,	'Banco Credit Agricole Brasil S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (505,	'Banco Credit Suisse (Brasil) S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (69,	'Banco Crefisa S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (3,	'B,anco da Amazônia S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (83,	'Banco da China Brasil S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (707,	'Banco Daycoval S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (707,	'Banco Daycoval S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (51,	'Banco de Desenvolvimento do Espírito Santo S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (300,	'Banco de La Nacion Argentina')
INSERT INTO bancos (Codigo, Nome) VALUES (495,	'Banco de La Provincia de Buenos Aires')
INSERT INTO bancos (Codigo, Nome) VALUES (494,	'Banco de La Republica Oriental del Uruguay')
INSERT INTO bancos (Codigo, Nome) VALUES (335,	'Banco Digio S.A')
INSERT INTO bancos (Codigo, Nome) VALUES (1,	'B,anco do Brasil S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (47,	'Banco do Estado de Sergipe S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (37,	'Banco do Estado do Pará S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (41,	'Banco do Estado do Rio Grande do Sul S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (4,	'B,anco do Nordeste do Brasil S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (196,	'Banco Fair Corretora de Câmbio S.A')
INSERT INTO bancos (Codigo, Nome) VALUES (265,	'Banco Fator S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (224,	'Banco Fibra S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (626,	'Banco Ficsa S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (94,	'Banco Finaxis S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (612,	'Banco Guanabara S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (12,	'Banco Inbursa S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (604,	'Banco Industrial do Brasil S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (653,	'Banco Indusval S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (77,	'Banco Inter S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (249,	'Banco Investcred Unibanco S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (184,	'Banco Itaú BBA S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (29,	'Banco Itaú Consignado S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (479,	'Banco ItauBank S.A')
INSERT INTO bancos (Codigo, Nome) VALUES (376,	'Banco J. P. Morgan S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (74,	'Banco J. Safra S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (217,	'Banco John Deere S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (76,	'Banco KDB S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (757,	'Banco KEB HANA do Brasil S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (600,	'Banco Luso Brasileiro S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (243,	'Banco Máxima S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (720,	'Banco Maxinvest S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (389,	'Banco Mercantil de Investimentos S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (389,	'Banco Mercantil do Brasil S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (370,	'Banco Mizuho do Brasil S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (746,	'Banco Modal S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (66,	'Banco Morgan Stanley S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (456,	'Banco MUFG Brasil S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (7,	'B,anco Nacional de Desenvolvimento Econômico e Social – BNDES')
INSERT INTO bancos (Codigo, Nome) VALUES (169,	'Banco Olé Bonsucesso Consignado S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (111,	'Banco Oliveira Trust Dtvm S.A')
INSERT INTO bancos (Codigo, Nome) VALUES (79,	'Banco Original do Agronegócio S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (212,	'Banco Original S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (712,	'Banco Ourinvest S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (623,	'Banco PAN S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (611,	'Banco Paulista S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (643,	'Banco Pine S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (658,	'Banco Porto Real de Investimentos S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (747,	'Banco Rabobank International Brasil S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (633,	'Banco Rendimento S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (741,	'Banco Ribeirão Preto S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (120,	'Banco Rodobens S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (422,	'Banco Safra S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (33,	'Banco Santander (Brasil) S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (743,	'Banco Semear S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (754,	'Banco Sistema S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (630,	'Banco Smartbank S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (366,	'Banco Société Générale Brasil S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (637,	'Banco Sofisa S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (464,	'Banco Sumitomo Mitsui Brasileiro S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (82,	'Banco Topázio S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (634,	'Banco Triângulo S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (18,	'Banco Tricury S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (655,	'Banco Votorantim S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (610,	'Banco VR S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (119,	'Banco Western Union do Brasil S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (124,	'Banco Woori Bank do Brasil S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (348,	'Banco Xp S/A')
INSERT INTO bancos (Codigo, Nome) VALUES (81,	'BancoSeguro S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (21,	'BANESTES S.A. Banco do Estado do Espírito Santo')
INSERT INTO bancos (Codigo, Nome) VALUES (755,	'Bank of America Merrill Lynch Banco Múltiplo S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (268,	'Barigui Companhia Hipotecária')
INSERT INTO bancos (Codigo, Nome) VALUES (250,	'BCV – Banco de Crédito e Varejo S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (144,	'BEXS Banco de Câmbio S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (253,	'Bexs Corretora de Câmbio S/A')
INSERT INTO bancos (Codigo, Nome) VALUES (134,	'Bgc Liquidez Dtvm Ltda')
INSERT INTO bancos (Codigo, Nome) VALUES (17,	'BNY Mellon Banco S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (301,	'Bpp Instituição De Pagamentos S.A')
INSERT INTO bancos (Codigo, Nome) VALUES (126,	'BR Partners Banco de Investimento S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (70,	'BRB – Banco de Brasília S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (92,	'Brickell S.A. Crédito, Financiamento e Investimento')
INSERT INTO bancos (Codigo, Nome) VALUES (173,	'BRL Trust Distribuidora de Títulos e Valores Mobiliários S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (142,	'Broker Brasil Cc Ltda')
INSERT INTO bancos (Codigo, Nome) VALUES (292,	'BS2 Distribuidora de Títulos e Valores Mobiliários S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (11,	'C.Suisse Hedging-Griffo Cv S.A (Credit Suisse)')
INSERT INTO bancos (Codigo, Nome) VALUES (104,	'Caixa Econômica Federal')
INSERT INTO bancos (Codigo, Nome) VALUES (288,	'Carol Distribuidora de Títulos e Valor Mobiliários Ltda')
INSERT INTO bancos (Codigo, Nome) VALUES (130,	'Caruana Scfi')
INSERT INTO bancos (Codigo, Nome) VALUES (159,	'Casa Credito S.A')
INSERT INTO bancos (Codigo, Nome) VALUES (16,	'Ccm Desp Trâns Sc E Rs')
INSERT INTO bancos (Codigo, Nome) VALUES (89,	'Ccr Reg Mogiana')
INSERT INTO bancos (Codigo, Nome) VALUES (114,	'Central Cooperativa De Crédito No Estado Do Espírito Santo')
INSERT INTO bancos (Codigo, Nome) VALUES (320,	'China Construction Bank (Brasil) Banco Múltiplo S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (477,	'Citibank N.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (180,	'Cm Capital Markets Cctvm Ltda')
INSERT INTO bancos (Codigo, Nome) VALUES (127,	'Codepe Cvc S.A')
INSERT INTO bancos (Codigo, Nome) VALUES (163,	'Commerzbank Brasil S.A. – Banco Múltiplo')
INSERT INTO bancos (Codigo, Nome) VALUES (60,	'Confidence Cc S.A')
INSERT INTO bancos (Codigo, Nome) VALUES (85,	'Coop Central Ailos')
INSERT INTO bancos (Codigo, Nome) VALUES (97,	'Cooperativa Central de Crédito Noroeste Brasileiro Ltda.')
INSERT INTO bancos (Codigo, Nome) VALUES (085,	'Cooperativa Central de Crédito Urbano-CECRED')
INSERT INTO bancos (Codigo, Nome) VALUES (090,	'Cooperativa Central de Economia e Crédito Mutuo – SICOOB UNIMAIS')
INSERT INTO bancos (Codigo, Nome) VALUES (087,	'Cooperativa Central de Economia e Crédito Mútuo das Unicredsde Santa Catarina e Paraná')
INSERT INTO bancos (Codigo, Nome) VALUES (089,	'Cooperativa de Crédito Rural da Região da Mogiana')
INSERT INTO bancos (Codigo, Nome) VALUES (286,	'Cooperativa de Crédito Rural De Ouro')
INSERT INTO bancos (Codigo, Nome) VALUES (279,	'Cooperativa de Crédito Rural de Primavera Do Leste')
INSERT INTO bancos (Codigo, Nome) VALUES (273,	'Cooperativa de Crédito Rural de São Miguel do Oeste – Sulcredi/São Miguel')
INSERT INTO bancos (Codigo, Nome) VALUES (98,	'Credialiança Ccr')
INSERT INTO bancos (Codigo, Nome) VALUES (098,	'CREDIALIANÇA COOPERATIVA DE CRÉDITO RURAL')
INSERT INTO bancos (Codigo, Nome) VALUES (10,	'Credicoamo')
INSERT INTO bancos (Codigo, Nome) VALUES (133,	'Cresol Confederação')
INSERT INTO bancos (Codigo, Nome) VALUES (182,	'Dacasa Financeira S/A')
INSERT INTO bancos (Codigo, Nome) VALUES (487,	'Deutsche Bank S.A. – Banco Alemão')
INSERT INTO bancos (Codigo, Nome) VALUES (140,	'Easynvest – Título Cv S.A')
INSERT INTO bancos (Codigo, Nome) VALUES (149,	'Facta S.A. Cfi')
INSERT INTO bancos (Codigo, Nome) VALUES (285,	'Frente Corretora de Câmbio Ltda.')
INSERT INTO bancos (Codigo, Nome) VALUES (278,	'Genial Investimentos Corretora de Valores Mobiliários S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (138,	'Get Money Cc Ltda')
INSERT INTO bancos (Codigo, Nome) VALUES (64,	'Goldman Sachs do Brasil Banco Múltiplo S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (177,	'Guide Investimentos S.A. Corretora de Valores')
INSERT INTO bancos (Codigo, Nome) VALUES (146,	'Guitta Corretora de Câmbio Ltda')
INSERT INTO bancos (Codigo, Nome) VALUES (78,	'Haitong Banco de Investimento do Brasil S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (62,	'Hipercard Banco Múltiplo S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (189,	'HS Financeira S/A Crédito, Financiamento e Investimentos')
INSERT INTO bancos (Codigo, Nome) VALUES (269,	'HSBC Brasil S.A. – Banco de Investimento')
INSERT INTO bancos (Codigo, Nome) VALUES (271,	'IB Corretora de Câmbio, Títulos e Valores Mobiliários S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (157,	'Icap Do Brasil Ctvm Ltda')
INSERT INTO bancos (Codigo, Nome) VALUES (132,	'ICBC do Brasil Banco Múltiplo S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (492,	'ING Bank N.V.')
INSERT INTO bancos (Codigo, Nome) VALUES (139,	'Intesa Sanpaolo Brasil S.A. – Banco Múltiplo')
INSERT INTO bancos (Codigo, Nome) VALUES (652,	'Itaú Unibanco Holding S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (341,	'Itaú Unibanco S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (488,	'JPMorgan Chase Bank, National Association')
INSERT INTO bancos (Codigo, Nome) VALUES (399,	'Kirton Bank S.A. – Banco Múltiplo')
INSERT INTO bancos (Codigo, Nome) VALUES (293,	'Lastro RDV Distribuidora de Títulos e Valores Mobiliários Ltda.')
INSERT INTO bancos (Codigo, Nome) VALUES (105,	'Lecca Crédito, Financiamento e Investimento S/A')
INSERT INTO bancos (Codigo, Nome) VALUES (145,	'Levycam Ccv Ltda')
INSERT INTO bancos (Codigo, Nome) VALUES (113,	'Magliano S.A')
INSERT INTO bancos (Codigo, Nome) VALUES (323,	'Mercado Pago – Conta Do Mercado Livre')
INSERT INTO bancos (Codigo, Nome) VALUES (128,	'MS Bank S.A. Banco de Câmbio')
INSERT INTO bancos (Codigo, Nome) VALUES (137,	'Multimoney Cc Ltda')
INSERT INTO bancos (Codigo, Nome) VALUES (14,	'Natixis Brasil S.A. Banco Múltiplo')
INSERT INTO bancos (Codigo, Nome) VALUES (191,	'Nova Futura Corretora de Títulos e Valores Mobiliários Ltda.')
INSERT INTO bancos (Codigo, Nome) VALUES (753,	'Novo Banco Continental S.A. – Banco Múltiplo')
INSERT INTO bancos (Codigo, Nome) VALUES (260,	'Nu Pagamentos S.A (Nubank)')
INSERT INTO bancos (Codigo, Nome) VALUES (613,	'Omni Banco S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (613,	'Omni Banco S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (290,	'Pagseguro Internet S.A')
INSERT INTO bancos (Codigo, Nome) VALUES (254,	'Paraná Banco S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (326,	'Parati – Crédito Financiamento e Investimento S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (194,	'Parmetal Distribuidora de Títulos e Valores Mobiliários Ltda')
INSERT INTO bancos (Codigo, Nome) VALUES (174,	'Pernambucanas Financ S.A')
INSERT INTO bancos (Codigo, Nome) VALUES (100,	'Planner Corretora De Valores S.A')
INSERT INTO bancos (Codigo, Nome) VALUES (125,	'Plural S.A. – Banco Múltiplo')
INSERT INTO bancos (Codigo, Nome) VALUES (93,	'Pólocred Scmepp Ltda')
INSERT INTO bancos (Codigo, Nome) VALUES (108,	'Portocred S.A')
INSERT INTO bancos (Codigo, Nome) VALUES (283,	'Rb Capital Investimentos Dtvm Ltda')
INSERT INTO bancos (Codigo, Nome) VALUES (101,	'Renascenca Dtvm Ltda')
INSERT INTO bancos (Codigo, Nome) VALUES (270,	'Sagitur Corretora de Câmbio Ltda.')
INSERT INTO bancos (Codigo, Nome) VALUES (751,	'Scotiabank Brasil S.A. Banco Múltiplo')
INSERT INTO bancos (Codigo, Nome) VALUES (276,	'Senff S.A. – Crédito, Financiamento e Investimento')
INSERT INTO bancos (Codigo, Nome) VALUES (545,	'Senso Ccvm S.A')
INSERT INTO bancos (Codigo, Nome) VALUES (190,	'Servicoop')
INSERT INTO bancos (Codigo, Nome) VALUES (183,	'Socred S.A')
INSERT INTO bancos (Codigo, Nome) VALUES (299,	'Sorocred Crédito, Financiamento e Investimento S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (118,	'Standard Chartered Bank (Brasil) S/A–Bco Invest.')
INSERT INTO bancos (Codigo, Nome) VALUES (197,	'Stone Pagamentos S.A')
INSERT INTO bancos (Codigo, Nome) VALUES (340,	'Super Pagamentos e Administração de Meios Eletrônicos S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (95,	'Travelex Banco de Câmbio S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (143,	'Treviso Corretora de Câmbio S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (131,	'Tullett Prebon Brasil Cvc Ltda')
INSERT INTO bancos (Codigo, Nome) VALUES (129,	'UBS Brasil Banco de Investimento S.A.')
INSERT INTO bancos (Codigo, Nome) VALUES (91,	'Unicred Central do Rio Grande do Sul')
INSERT INTO bancos (Codigo, Nome) VALUES (136,	'Unicred Cooperativa')
INSERT INTO bancos (Codigo, Nome) VALUES (99,	'UNIPRIME Central – Central Interestadual de Cooperativas de Crédito Ltda.')
INSERT INTO bancos (Codigo, Nome) VALUES (84,	'Uniprime Norte do Paraná – Coop de Economia eCrédito Mútuo dos Médicos, Profissionais das Ciências')
INSERT INTO bancos (Codigo, Nome) VALUES (298,	'Vips Cc Ltda')
INSERT INTO bancos (Codigo, Nome) VALUES (310,	'Vortx Distribuidora de Títulos e Valores Mobiliários Ltda')
INSERT INTO bancos (Codigo, Nome) VALUES (102,	'Xp Investimentos S.A')