// <auto-generated />
using System;
using CentralDasOngs.Dados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CentralDasOngs.Migrations
{
    [DbContext(typeof(CentralDasOngsContext))]
    partial class CentralDasOngsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CentralDasOngs.Models.Banco", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("bancos");
                });

            modelBuilder.Entity("CentralDasOngs.Models.DadoBancario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Agencia")
                        .HasColumnType("int");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Operacao")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioOngCnpj")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo");

                    b.HasIndex("UsuarioOngCnpj");

                    b.ToTable("DadosBancarios");
                });

            modelBuilder.Entity("CentralDasOngs.Models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroEndereco")
                        .HasColumnType("int");

                    b.Property<string>("Uf")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UsuarioOngCnpj")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UsuarioVoluntarioCpf")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Uf");

                    b.HasIndex("UsuarioOngCnpj");

                    b.HasIndex("UsuarioVoluntarioCpf");

                    b.ToTable("enderecos");
                });

            modelBuilder.Entity("CentralDasOngs.Models.UnidadeFederativa", b =>
                {
                    b.Property<string>("Uf")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("uf");

                    b.HasKey("Uf");

                    b.ToTable("ufs");
                });

            modelBuilder.Entity("CentralDasOngs.Models.UsuarioOng", b =>
                {
                    b.Property<string>("Cnpj_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Cnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Cnpj_Id");

                    b.ToTable("UsuariosOng");
                });

            modelBuilder.Entity("CentralDasOngs.Models.UsuarioVoluntario", b =>
                {
                    b.Property<string>("Cpf_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Cpf_Id");

                    b.ToTable("UsuariosVoluntarios");
                });

            modelBuilder.Entity("CentralDasOngs.Models.DadoBancario", b =>
                {
                    b.HasOne("CentralDasOngs.Models.Banco", "Banco")
                        .WithMany("Id")
                        .HasForeignKey("Codigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralDasOngs.Models.UsuarioOng", "UsuarioOng")
                        .WithMany()
                        .HasForeignKey("UsuarioOngCnpj");

                    b.Navigation("Banco");

                    b.Navigation("UsuarioOng");
                });

            modelBuilder.Entity("CentralDasOngs.Models.Endereco", b =>
                {
                    b.HasOne("CentralDasOngs.Models.UnidadeFederativa", "UnidadeFederativa")
                        .WithMany("Id")
                        .HasForeignKey("Uf");

                    b.HasOne("CentralDasOngs.Models.UsuarioOng", "UsuarioOng")
                        .WithMany()
                        .HasForeignKey("UsuarioOngCnpj");

                    b.HasOne("CentralDasOngs.Models.UsuarioVoluntario", "UsuarioVoluntario")
                        .WithMany()
                        .HasForeignKey("UsuarioVoluntarioCpf");

                    b.Navigation("UnidadeFederativa");

                    b.Navigation("UsuarioOng");

                    b.Navigation("UsuarioVoluntario");
                });

            modelBuilder.Entity("CentralDasOngs.Models.Banco", b =>
                {
                    b.Navigation("Id");
                });

            modelBuilder.Entity("CentralDasOngs.Models.UnidadeFederativa", b =>
                {
                    b.Navigation("Id");
                });
#pragma warning restore 612, 618
        }
    }
}
