SET IDENTITY_INSERT Banks ON;

INSERT INTO Banks (Code, Name) VALUES (117,	'Advanced Cc Ltda');
INSERT INTO Banks (Code, Name) VALUES (172,	'Albatross Ccv S.A');
INSERT INTO Banks (Code, Name) VALUES (188,	'Ativa Investimentos S.A');
INSERT INTO Banks (Code, Name) VALUES (280,	'Avista S.A. Crédito, Financiamento e Investimento');
INSERT INTO Banks (Code, Name) VALUES (80,	'B&T Cc Ltda');
INSERT INTO Banks (Code, Name) VALUES (654,	'Banco A.J.Renner S.A.');
INSERT INTO Banks (Code, Name) VALUES (75,	'Banco ABN AMRO S.A');
INSERT INTO Banks (Code, Name) VALUES (121,	'Banco Agibank S.A.');
INSERT INTO Banks (Code, Name) VALUES (25,	'Banco Alfa S.A.');
INSERT INTO Banks (Code, Name) VALUES (641,	'Banco Alvorada S.A.');
INSERT INTO Banks (Code, Name) VALUES (65,	'Banco Andbank (Brasil) S.A.');
INSERT INTO Banks (Code, Name) VALUES (213,	'Banco Arbi S.A.');
INSERT INTO Banks (Code, Name) VALUES (96,	'Banco B3 S.A.');
INSERT INTO Banks (Code, Name) VALUES (24,	'Banco BANDEPE S.A.');
INSERT INTO Banks (Code, Name) VALUES (318,	'Banco BMG S.A.');
INSERT INTO Banks (Code, Name) VALUES (752,	'Banco BNP Paribas Brasil S.A.');
INSERT INTO Banks (Code, Name) VALUES (107,	'Banco BOCOM BBM S.A.');
INSERT INTO Banks (Code, Name) VALUES (63,	'Banco Bradescard S.A.');
INSERT INTO Banks (Code, Name) VALUES (36,	'Banco Bradesco BBI S.A.');
INSERT INTO Banks (Code, Name) VALUES (122,	'Banco Bradesco BERJ S.A.');
INSERT INTO Banks (Code, Name) VALUES (204,	'Banco Bradesco Cartões S.A.');
INSERT INTO Banks (Code, Name) VALUES (394,	'Banco Bradesco Financiamentos S.A.');
INSERT INTO Banks (Code, Name) VALUES (237,	'Banco Bradesco S.A.');
INSERT INTO Banks (Code, Name) VALUES (218,	'Banco BS2 S.A.');
INSERT INTO Banks (Code, Name) VALUES (208,	'Banco BTG Pactual S.A.');
INSERT INTO Banks (Code, Name) VALUES (336,	'Banco C6 S.A – C6 Bank');
INSERT INTO Banks (Code, Name) VALUES (473,	'Banco Caixa Geral – Brasil S.A.');
INSERT INTO Banks (Code, Name) VALUES (412,	'Banco Capital S.A.');
INSERT INTO Banks (Code, Name) VALUES (40,	'Banco Cargill S.A.');
INSERT INTO Banks (Code, Name) VALUES (368,	'Banco Carrefour');
INSERT INTO Banks (Code, Name) VALUES (266,	'Banco Cédula S.A.');
INSERT INTO Banks (Code, Name) VALUES (739,	'Banco Cetelem S.A.');
INSERT INTO Banks (Code, Name) VALUES (233,	'Banco Cifra S.A.');
INSERT INTO Banks (Code, Name) VALUES (745,	'Banco Citibank S.A.');
INSERT INTO Banks (Code, Name) VALUES (241,	'Banco Clássico S.A.');
INSERT INTO Banks (Code, Name) VALUES (756,	'Banco Cooperativo do Brasil S.A. – BANCOOB');
INSERT INTO Banks (Code, Name) VALUES (748,	'Banco Cooperativo Sicredi S.A.');
INSERT INTO Banks (Code, Name) VALUES (222,	'Banco Credit Agricole Brasil S.A.');
INSERT INTO Banks (Code, Name) VALUES (505,	'Banco Credit Suisse (Brasil) S.A.');
INSERT INTO Banks (Code, Name) VALUES (69,	'Banco Crefisa S.A.');
INSERT INTO Banks (Code, Name) VALUES (3,	'Banco da Amazônia S.A.');
INSERT INTO Banks (Code, Name) VALUES (83,	'Banco da China Brasil S.A.');
INSERT INTO Banks (Code, Name) VALUES (707,	'Banco Daycoval S.A.');
INSERT INTO Banks (Code, Name) VALUES (51,	'Banco de Desenvolvimento do Espírito Santo S.A.');
INSERT INTO Banks (Code, Name) VALUES (300,	'Banco de La Nacion Argentina');
INSERT INTO Banks (Code, Name) VALUES (495,	'Banco de La Provincia de Buenos Aires');
INSERT INTO Banks (Code, Name) VALUES (494,	'Banco de La Republica Oriental del Uruguay');
INSERT INTO Banks (Code, Name) VALUES (335,	'Banco Digio S.A');
INSERT INTO Banks (Code, Name) VALUES (1,	'Banco do Brasil S.A.');
INSERT INTO Banks (Code, Name) VALUES (47,	'Banco do Estado de Sergipe S.A.');
INSERT INTO Banks (Code, Name) VALUES (37,	'Banco do Estado do Pará S.A.');
INSERT INTO Banks (Code, Name) VALUES (41,	'Banco do Estado do Rio Grande do Sul S.A.');
INSERT INTO Banks (Code, Name) VALUES (4,	'Banco do Nordeste do Brasil S.A.');
INSERT INTO Banks (Code, Name) VALUES (196,	'Banco Fair Corretora de Câmbio S.A');
INSERT INTO Banks (Code, Name) VALUES (265,	'Banco Fator S.A.');
INSERT INTO Banks (Code, Name) VALUES (224,	'Banco Fibra S.A.');
INSERT INTO Banks (Code, Name) VALUES (626,	'Banco Ficsa S.A.');
INSERT INTO Banks (Code, Name) VALUES (94,	'Banco Finaxis S.A.');
INSERT INTO Banks (Code, Name) VALUES (612,	'Banco Guanabara S.A.');
INSERT INTO Banks (Code, Name) VALUES (12,	'Banco Inbursa S.A.');
INSERT INTO Banks (Code, Name) VALUES (604,	'Banco Industrial do Brasil S.A.');
INSERT INTO Banks (Code, Name) VALUES (653,	'Banco Indusval S.A.');
INSERT INTO Banks (Code, Name) VALUES (77,	'Banco Inter S.A.');
INSERT INTO Banks (Code, Name) VALUES (249,	'Banco Investcred Unibanco S.A.');
INSERT INTO Banks (Code, Name) VALUES (184,	'Banco Itaú BBA S.A.');
INSERT INTO Banks (Code, Name) VALUES (29,	'Banco Itaú Consignado S.A.');
INSERT INTO Banks (Code, Name) VALUES (479,	'Banco ItauBank S.A');
INSERT INTO Banks (Code, Name) VALUES (376,	'Banco J. P. Morgan S.A.');
INSERT INTO Banks (Code, Name) VALUES (74,	'Banco J. Safra S.A.');
INSERT INTO Banks (Code, Name) VALUES (217,	'Banco John Deere S.A.');
INSERT INTO Banks (Code, Name) VALUES (76,	'Banco KDB S.A.');
INSERT INTO Banks (Code, Name) VALUES (757,	'Banco KEB HANA do Brasil S.A.');
INSERT INTO Banks (Code, Name) VALUES (600,	'Banco Luso Brasileiro S.A.');
INSERT INTO Banks (Code, Name) VALUES (243,	'Banco Máxima S.A.');
INSERT INTO Banks (Code, Name) VALUES (720,	'Banco Maxinvest S.A.');
INSERT INTO Banks (Code, Name) VALUES (389,	'Banco Mercantil do Brasil S.A.');
INSERT INTO Banks (Code, Name) VALUES (370,	'Banco Mizuho do Brasil S.A.');
INSERT INTO Banks (Code, Name) VALUES (746,	'Banco Modal S.A.');
INSERT INTO Banks (Code, Name) VALUES (66,	'Banco Morgan Stanley S.A.');
INSERT INTO Banks (Code, Name) VALUES (456,	'Banco MUFG Brasil S.A.');
INSERT INTO Banks (Code, Name) VALUES (7,	'Banco Nacional de Desenvolvimento Econômico e Social – BNDES');
INSERT INTO Banks (Code, Name) VALUES (169,	'Banco Olé Bonsucesso Consignado S.A.');
INSERT INTO Banks (Code, Name) VALUES (111,	'Banco Oliveira Trust Dtvm S.A');
INSERT INTO Banks (Code, Name) VALUES (79,	'Banco Original do Agronegócio S.A.');
INSERT INTO Banks (Code, Name) VALUES (212,	'Banco Original S.A.');
INSERT INTO Banks (Code, Name) VALUES (712,	'Banco Ourinvest S.A.');
INSERT INTO Banks (Code, Name) VALUES (623,	'Banco PAN S.A.');
INSERT INTO Banks (Code, Name) VALUES (611,	'Banco Paulista S.A.');
INSERT INTO Banks (Code, Name) VALUES (643,	'Banco Pine S.A.');
INSERT INTO Banks (Code, Name) VALUES (658,	'Banco Porto Real de Investimentos S.A.');
INSERT INTO Banks (Code, Name) VALUES (747,	'Banco Rabobank International Brasil S.A.');
INSERT INTO Banks (Code, Name) VALUES (633,	'Banco Rendimento S.A.');
INSERT INTO Banks (Code, Name) VALUES (741,	'Banco Ribeirão Preto S.A.');
INSERT INTO Banks (Code, Name) VALUES (120,	'Banco Rodobens S.A.');
INSERT INTO Banks (Code, Name) VALUES (422,	'Banco Safra S.A.');
INSERT INTO Banks (Code, Name) VALUES (33,	'Banco Santander (Brasil) S.A.');
INSERT INTO Banks (Code, Name) VALUES (743,	'Banco Semear S.A.');
INSERT INTO Banks (Code, Name) VALUES (754,	'Banco Sistema S.A.');
INSERT INTO Banks (Code, Name) VALUES (630,	'Banco Smartbank S.A.');
INSERT INTO Banks (Code, Name) VALUES (366,	'Banco Société Générale Brasil S.A.');
INSERT INTO Banks (Code, Name) VALUES (637,	'Banco Sofisa S.A.');
INSERT INTO Banks (Code, Name) VALUES (464,	'Banco Sumitomo Mitsui Brasileiro S.A.');
INSERT INTO Banks (Code, Name) VALUES (82,	'Banco Topázio S.A.');
INSERT INTO Banks (Code, Name) VALUES (634,	'Banco Triângulo S.A.');
INSERT INTO Banks (Code, Name) VALUES (18,	'Banco Tricury S.A.');
INSERT INTO Banks (Code, Name) VALUES (655,	'Banco Votorantim S.A.');
INSERT INTO Banks (Code, Name) VALUES (610,	'Banco VR S.A.');
INSERT INTO Banks (Code, Name) VALUES (119,	'Banco Western Union do Brasil S.A.');
INSERT INTO Banks (Code, Name) VALUES (124,	'Banco Woori Bank do Brasil S.A.');
INSERT INTO Banks (Code, Name) VALUES (348,	'Banco Xp S/A');
INSERT INTO Banks (Code, Name) VALUES (81,	'Banco Seguro S.A.') ;
INSERT INTO Banks (Code, Name) VALUES (21,	'BANESTES S.A. Banco do Estado do Espírito Santo');
INSERT INTO Banks (Code, Name) VALUES (755,	'Bank of America Merrill Lynch Banco Múltiplo S.A.');
INSERT INTO Banks (Code, Name) VALUES (268,	'Barigui Companhia Hipotecária');
INSERT INTO Banks (Code, Name) VALUES (250,	'BCV – Banco de Crédito e Varejo S.A.');
INSERT INTO Banks (Code, Name) VALUES (144,	'BEXS Banco de Câmbio S.A.');
INSERT INTO Banks (Code, Name) VALUES (253,	'Bexs Corretora de Câmbio S/A');
INSERT INTO Banks (Code, Name) VALUES (134,	'Bgc Liquidez Dtvm Ltda');
INSERT INTO Banks (Code, Name) VALUES (17,	'BNY Mellon Banco S.A.');
INSERT INTO Banks (Code, Name) VALUES (301,	'Bpp Instituição De Pagamentos S.A');
INSERT INTO Banks (Code, Name) VALUES (126,	'BR Partners Banco de Investimento S.A.');
INSERT INTO Banks (Code, Name) VALUES (70,	'BRB – Banco de Brasília S.A.');
INSERT INTO Banks (Code, Name) VALUES (92,	'Brickell S.A. Crédito, Financiamento e Investimento');
INSERT INTO Banks (Code, Name) VALUES (173,	'BRL Trust Distribuidora de Títulos e Valores Mobiliários S.A.');
INSERT INTO Banks (Code, Name) VALUES (142,	'Broker Brasil Cc Ltda');
INSERT INTO Banks (Code, Name) VALUES (292,	'BS2 Distribuidora de Títulos e Valores Mobiliários S.A.');
INSERT INTO Banks (Code, Name) VALUES (11,	'C.Suisse Hedging-Griffo Cv S.A (Credit Suisse)');
INSERT INTO Banks (Code, Name) VALUES (104,	'Caixa Econômica Federal');
INSERT INTO Banks (Code, Name) VALUES (288,	'Carol Distribuidora de Títulos e Valor Mobiliários Ltda');
INSERT INTO Banks (Code, Name) VALUES (130,	'Caruana Scfi');
INSERT INTO Banks (Code, Name) VALUES (159,	'Casa Credito S.A');
INSERT INTO Banks (Code, Name) VALUES (16,	'Ccm Desp Trâns Sc E Rs');
INSERT INTO Banks (Code, Name) VALUES (89,	'Ccr Reg Mogiana');
INSERT INTO Banks (Code, Name) VALUES (114,	'Central Cooperativa De Crédito No Estado Do Espírito Santo');
INSERT INTO Banks (Code, Name) VALUES (320,	'China Construction Bank (Brasil) Banco Múltiplo S.A.');
INSERT INTO Banks (Code, Name) VALUES (477,	'Citibank N.A.');
INSERT INTO Banks (Code, Name) VALUES (180,	'Cm Capital Markets Cctvm Ltda');
INSERT INTO Banks (Code, Name) VALUES (127,	'Codepe Cvc S.A');
INSERT INTO Banks (Code, Name) VALUES (163,	'Commerzbank Brasil S.A. – Banco Múltiplo');
INSERT INTO Banks (Code, Name) VALUES (60,	'Confidence Cc S.A');
INSERT INTO Banks (Code, Name) VALUES (85,	'Coop Central Ailos');
INSERT INTO Banks (Code, Name) VALUES (97,	'Cooperativa Central de Crédito Noroeste Brasileiro Ltda.');
INSERT INTO Banks (Code, Name) VALUES (286,	'Cooperativa de Crédito Rural De Ouro');
INSERT INTO Banks (Code, Name) VALUES (279,	'Cooperativa de Crédito Rural de Primavera Do Leste');
INSERT INTO Banks (Code, Name) VALUES (273,	'Cooperativa de Crédito Rural de São Miguel do Oeste – Sulcredi/São Miguel');
INSERT INTO Banks (Code, Name) VALUES (98,	'Credialiança Ccr');
INSERT INTO Banks (Code, Name) VALUES (10,	'Credicoamo');
INSERT INTO Banks (Code, Name) VALUES (133,	'Cresol Confederação');
INSERT INTO Banks (Code, Name) VALUES (182,	'Dacasa Financeira S/A');
INSERT INTO Banks (Code, Name) VALUES (487,	'Deutsche Bank S.A. – Banco Alemão');
INSERT INTO Banks (Code, Name) VALUES (140,	'Easynvest – Título Cv S.A');
INSERT INTO Banks (Code, Name) VALUES (149,	'Facta S.A. Cfi');
INSERT INTO Banks (Code, Name) VALUES (285,	'Frente Corretora de Câmbio Ltda.');
INSERT INTO Banks (Code, Name) VALUES (278,	'Genial Investimentos Corretora de Valores Mobiliários S.A.');
INSERT INTO Banks (Code, Name) VALUES (138,	'Get Money Cc Ltda');
INSERT INTO Banks (Code, Name) VALUES (64,	'Goldman Sachs do Brasil Banco Múltiplo S.A.');
INSERT INTO Banks (Code, Name) VALUES (177,	'Guide Investimentos S.A. Corretora de Valores');
INSERT INTO Banks (Code, Name) VALUES (146,	'Guitta Corretora de Câmbio Ltda');
INSERT INTO Banks (Code, Name) VALUES (78,	'Haitong Banco de Investimento do Brasil S.A.');
INSERT INTO Banks (Code, Name) VALUES (62,	'Hipercard Banco Múltiplo S.A.');
INSERT INTO Banks (Code, Name) VALUES (189,	'HS Financeira S/A Crédito, Financiamento e Investimentos');
INSERT INTO Banks (Code, Name) VALUES (269,	'HSBC Brasil S.A. – Banco de Investimento');
INSERT INTO Banks (Code, Name) VALUES (271,	'IB Corretora de Câmbio, Títulos e Valores Mobiliários S.A.');
INSERT INTO Banks (Code, Name) VALUES (157,	'Icap Do Brasil Ctvm Ltda');
INSERT INTO Banks (Code, Name) VALUES (132,	'ICBC do Brasil Banco Múltiplo S.A.');
INSERT INTO Banks (Code, Name) VALUES (492,	'ING Bank N.V.');
INSERT INTO Banks (Code, Name) VALUES (139,	'Intesa Sanpaolo Brasil S.A. – Banco Múltiplo');
INSERT INTO Banks (Code, Name) VALUES (652,	'Itaú Unibanco Holding S.A.');
INSERT INTO Banks (Code, Name) VALUES (341,	'Itaú Unibanco S.A.');
INSERT INTO Banks (Code, Name) VALUES (488,	'JPMorgan Chase Bank, National Association');
INSERT INTO Banks (Code, Name) VALUES (399,	'Kirton Bank S.A. – Banco Múltiplo');
INSERT INTO Banks (Code, Name) VALUES (293,	'Lastro RDV Distribuidora de Títulos e Valores Mobiliários Ltda.');
INSERT INTO Banks (Code, Name) VALUES (105,	'Lecca Crédito, Financiamento e Investimento S/A');
INSERT INTO Banks (Code, Name) VALUES (145,	'Levycam Ccv Ltda');
INSERT INTO Banks (Code, Name) VALUES (113,	'Magliano S.A');
INSERT INTO Banks (Code, Name) VALUES (323,	'Mercado Pago – Conta Do Mercado Livre');
INSERT INTO Banks (Code, Name) VALUES (128,	'MS Bank S.A. Banco de Câmbio');
INSERT INTO Banks (Code, Name) VALUES (137,	'Multimoney Cc Ltda');
INSERT INTO Banks (Code, Name) VALUES (14,	'Natixis Brasil S.A. Banco Múltiplo');
INSERT INTO Banks (Code, Name) VALUES (191,	'Nova Futura Corretora de Títulos e Valores Mobiliários Ltda.');
INSERT INTO Banks (Code, Name) VALUES (753,	'Novo Banco Continental S.A. – Banco Múltiplo');
INSERT INTO Banks (Code, Name) VALUES (260,	'Nu Pagamentos S.A (Nubank)');
INSERT INTO Banks (Code, Name) VALUES (613,	'Omni Banco S.A.');
INSERT INTO Banks (Code, Name) VALUES (290,	'Pagseguro Internet S.A');
INSERT INTO Banks (Code, Name) VALUES (254,	'Paraná Banco S.A.');
INSERT INTO Banks (Code, Name) VALUES (326,	'Parati – Crédito Financiamento e Investimento S.A.');
INSERT INTO Banks (Code, Name) VALUES (194,	'Parmetal Distribuidora de Títulos e Valores Mobiliários Ltda');
INSERT INTO Banks (Code, Name) VALUES (174,	'Pernambucanas Financ S.A');
INSERT INTO Banks (Code, Name) VALUES (100,	'Planner Corretora De Valores S.A');
INSERT INTO Banks (Code, Name) VALUES (125,	'Plural S.A. – Banco Múltiplo');
INSERT INTO Banks (Code, Name) VALUES (93,	'Pólocred Scmepp Ltda');
INSERT INTO Banks (Code, Name) VALUES (108,	'Portocred S.A');
INSERT INTO Banks (Code, Name) VALUES (283,	'Rb Capital Investimentos Dtvm Ltda');
INSERT INTO Banks (Code, Name) VALUES (101,	'Renascenca Dtvm Ltda');
INSERT INTO Banks (Code, Name) VALUES (270,	'Sagitur Corretora de Câmbio Ltda.');
INSERT INTO Banks (Code, Name) VALUES (751,	'Scotiabank Brasil S.A. Banco Múltiplo');
INSERT INTO Banks (Code, Name) VALUES (276,	'Senff S.A. – Crédito, Financiamento e Investimento');
INSERT INTO Banks (Code, Name) VALUES (545,	'Senso Ccvm S.A');
INSERT INTO Banks (Code, Name) VALUES (190,	'Servicoop');
INSERT INTO Banks (Code, Name) VALUES (183,	'Socred S.A');
INSERT INTO Banks (Code, Name) VALUES (299,	'Sorocred Crédito, Financiamento e Investimento S.A.');
INSERT INTO Banks (Code, Name) VALUES (118,	'Standard Chartered Bank (Brasil) S/A–Bco Invest.');
INSERT INTO Banks (Code, Name) VALUES (197,	'Stone Pagamentos S.A');
INSERT INTO Banks (Code, Name) VALUES (340,	'Super Pagamentos e Administração de Meios Eletrônicos S.A.');
INSERT INTO Banks (Code, Name) VALUES (95,	'Travelex Banco de Câmbio S.A.');
INSERT INTO Banks (Code, Name) VALUES (143,	'Treviso Corretora de Câmbio S.A.');
INSERT INTO Banks (Code, Name) VALUES (131,	'Tullett Prebon Brasil Cvc Ltda');
INSERT INTO Banks (Code, Name) VALUES (129,	'UBS Brasil Banco de Investimento S.A.');
INSERT INTO Banks (Code, Name) VALUES (91,	'Unicred Central do Rio Grande do Sul');
INSERT INTO Banks (Code, Name) VALUES (136,	'Unicred Cooperativa');
INSERT INTO Banks (Code, Name) VALUES (99,	'UNIPRIME Central – Central Interestadual de Cooperativas de Crédito Ltda.');
INSERT INTO Banks (Code, Name) VALUES (84,	'Uniprime Norte do Paraná – Coop de Economia eCrédito Mútuo dos Médicos, Profissionais das Ciências');
INSERT INTO Banks (Code, Name) VALUES (298,	'Vips Cc Ltda');
INSERT INTO Banks (Code, Name) VALUES (310,	'Vortx Distribuidora de Títulos e Valores Mobiliários Ltda');
INSERT INTO Banks (Code, Name) VALUES (102,	'Xp Investimentos S.A');