Insert into "UFs" ("Id","UF") values (1, 'AC');
Insert into "UFs" ("Id","UF") values (2, 'AL');
Insert into "UFs" ("Id","UF") values (3, 'AP');
Insert into "UFs" ("Id","UF") values (4, 'AM');
Insert into "UFs" ("Id","UF") values (5, 'BA');
Insert into "UFs" ("Id","UF") values (6, 'CE');
Insert into "UFs" ("Id","UF") values (7, 'DF');
Insert into "UFs" ("Id","UF") values (8, 'ES');
Insert into "UFs" ("Id","UF") values (9, 'GO');
Insert into "UFs" ("Id","UF") values (10,'MA');
Insert into "UFs" ("Id","UF") values (11,'MT');
Insert into "UFs" ("Id","UF") values (12,'MS');
Insert into "UFs" ("Id","UF") values (13,'MG');
Insert into "UFs" ("Id","UF") values (14,'PA');
Insert into "UFs" ("Id","UF") values (15,'PB');
Insert into "UFs" ("Id","UF") values (16,'PR');
Insert into "UFs" ("Id","UF") values (17,'PE');
Insert into "UFs" ("Id","UF") values (18,'PI');
Insert into "UFs" ("Id","UF") values (19,'RJ');
Insert into "UFs" ("Id","UF") values (20,'RN');
Insert into "UFs" ("Id","UF") values (21,'RS');
Insert into "UFs" ("Id","UF") values (22,'RO');
Insert into "UFs" ("Id","UF") values (23,'RR');
Insert into "UFs" ("Id","UF") values (24,'SC');
Insert into "UFs" ("Id","UF") values (25,'SP');
Insert into "UFs" ("Id","UF") values (26, 'SE');
Insert into "UFs" ("Id","UF") values (27,'TO');